#!/usr/bin/env python3
"""Legal-jargon glossary, mined from the statutes themselves.

A news story says 主管機關 / 通報義務人 / 目的事業主管機關 and assumes the reader
knows. Most don't. Taiwanese statutes almost always define their own terms in a
定義 article — 「本法所稱主管機關：在中央為…」 — so the glossary does not need to be
written by hand or generated by a model. It is extracted from the enacted text.

Output: `data/terms.json`, term -> the statutes that define it, with the exact
defining sentence and article.
"""

import json
import re
import sys
import urllib.request
import zipfile
from collections import defaultdict
from io import BytesIO
from pathlib import Path

DUMP = "https://law.moj.gov.tw/api/Ch/Law/JSON"
DATA = Path(__file__).resolve().parent.parent / "data"
UA = "Mozilla/5.0 (compatible; tw-law-blame/0.1; +https://github.com/Hakanai-AI/tw-law-blame)"

# 「本法所稱主管機關：在中央為…」 and 「本法所稱食品業者，指…」 are the two shapes.
# 條例/辦法/標準/細則 use their own self-reference, hence the alternation.
SELF = r"本(?:法|條例|辦法|標準|細則|通則|規則)所稱"
DEFN = re.compile(rf"{SELF}([^，,：:。；]{{2,12}})\s*[，,：:]\s*(?:指|謂)?\s*([^。]{{4,240}})。")

# The far more common shape is an enumerated 定義 article:
#   本法用詞，定義如下：一、食品：指供人飲食…。二、特殊營養食品：指…。
# Missing it costs most of the glossary — the 「本法所稱X」 form alone yields 580
# terms, this adds thousands.
ENUM_HEAD = re.compile(rf"(?:{SELF}|本(?:法|條例|辦法|標準|細則|通則|規則)用詞)"
                       r"[^：:。]{0,12}[：:]")
ITEM = re.compile(r"[一二三四五六七八九十]+、\s*([^：:。，]{2,14})\s*[：:]\s*([^。]{4,240})")


def ENUM_DEFN(body: str) -> list[tuple[str, str]]:
    if not ENUM_HEAD.search(body):
        return []
    return ITEM.findall(body)


# Terms so generic that a match says nothing useful to a reader.
STOP = {"用詞", "名詞", "用語", "本法", "各款", "前項", "其他", "定義如下"}


def load_dump() -> dict:
    req = urllib.request.Request(DUMP, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=180) as r:
        blob = r.read()
    with zipfile.ZipFile(BytesIO(blob)) as z:
        return json.loads(z.read("ChLaw.json").decode("utf-8-sig"))


def main() -> int:
    doc = load_dump()
    laws = doc["Laws"]
    if len(laws) < 500:
        print(f"FATAL: {len(laws)} statutes in dump", file=sys.stderr)
        return 1

    terms: dict[str, list] = defaultdict(list)
    for law in laws:
        for art in law.get("LawArticles", []):
            if art.get("ArticleType") != "A":
                continue
            body = " ".join((art.get("ArticleContent") or "").split())
            pairs = list(DEFN.findall(body))
            pairs += ENUM_DEFN(body)
            for term, meaning in pairs:
                term = term.strip()
                if term in STOP or len(term) < 2:
                    continue
                terms[term].append({
                    "law": law["LawName"],
                    "article": (art.get("ArticleNo") or "").strip(),
                    "text": meaning.strip()[:240],
                    "url": law.get("LawURL", ""),
                })

    # A term defined by 200 statutes is a drafting convention, not an
    # explanation. Keep the most-specific handful per term.
    out = {t: defs[:6] for t, defs in sorted(terms.items(), key=lambda kv: -len(kv[1]))}

    if len(out) < 200:
        print(f"FATAL: only {len(out)} terms extracted — regex likely broken", file=sys.stderr)
        return 1

    (DATA / "terms.json").write_text(json.dumps({
        "source": "全國法規資料庫 (law.moj.gov.tw)",
        "updated": doc.get("UpdateDate"),
        "count": len(out),
        "terms": out,
    }, ensure_ascii=False, separators=(",", ":")), encoding="utf-8")

    print(f"{len(out)} defined terms from {len(laws)} statutes")
    for t in list(out)[:12]:
        print(f"  {t}  ({len(terms[t])} statutes)  e.g. {out[t][0]['law']} {out[t][0]['article']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
